openapi: 3.0.0
info:
  title: Presence API
  version: 0.1.0
  description: Läsnäolojärjetelmän api
paths:
  '/areas/{area}/presence':
    post:
      summary: 'Lähetä läsnäoloilamisimen havainnot'
      parameters:
      - name: area
        in: path
        required: true
        schema:
          type: string 
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: Success
components:
  schemas:
    Message:
      type: object
      properties:
        tags:
          type: array
          description: 'Havaitut läsnäolotunnisteet'
          items:
            type: string